# Computation on NumPy Arrays

# Universal Functions

The NumPy operations can be made fast by converting them into vectorised operations. This is done through the usage of universal functions. NumPy provides convinient interface to the statically typed, compiled routine known as vectorised operations. This approach i designed to push the loop into the compiled layer that is behind the NumPy, which leads to faster execution.

These operations are defined through ufuncs, which mainly do the quick repeated operations on values in NumPy arrays. 

<b> Arithmetic operations<b>

Arithmetic operators can be applied directly on the ndarray.

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [2]:
a + 5  # add five to each array element

array([ 6,  7,  8,  9, 10])

In [3]:
a - 5

array([-4, -3, -2, -1,  0])

In [4]:
a * 5

array([ 5, 10, 15, 20, 25])

In [5]:
a/ 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
a // 5

array([0, 0, 0, 0, 1])

In [7]:
a ** 5

array([   1,   32,  243, 1024, 3125])

In [8]:
a % 5

array([1, 2, 3, 4, 0])

In [9]:
- a

array([-1, -2, -3, -4, -5])

Ufuncs are also available for the same operations.

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
np.add(a, 5)

array([ 6,  7,  8,  9, 10])

In [12]:
np.subtract(a, 5)

array([-4, -3, -2, -1,  0])

In [14]:
np.multiply(a, 5)

array([ 5, 10, 15, 20, 25])

In [15]:
np.divide(a , 5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.floor_divide(a, 5)

array([0, 0, 0, 0, 1])

In [21]:
11//5

2

In [23]:
np.floor_divide(11, 5)

2

In [24]:
np.power(a, 5)

array([   1,   32,  243, 1024, 3125])

In [25]:
np.mod(a, 5)

array([1, 2, 3, 4, 0])

In [26]:
np.negative(a)

array([-1, -2, -3, -4, -5])

<b> Absolute function<b>

In [27]:
a = np.array([-1, 3, -3, 4, -5])

In [28]:
abs(a)

array([1, 3, 3, 4, 5])

In [29]:
np.absolute(a)

array([1, 3, 3, 4, 5])

In [30]:
np.abs(a)

array([1, 3, 3, 4, 5])

<b> Exponents and Logarithmic functions<b>

In [32]:
x = np.array([1, 2, 3, 4, 5])

In [33]:
print("e^x   : " , np.exp(x))

e^x   :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [34]:
print("2^x   : " , np.exp2(x))

2^x   :  [ 2.  4.  8. 16. 32.]


In [35]:
print("3^x   : " , np.power(3, x))

3^x   :  [  3   9  27  81 243]


In [36]:
print("ln(x)   : ", np.log(x))

ln(x)   :  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [37]:
print("log2(x)   :  ", np.log2(x))

log2(x)   :   [0.         1.         1.5849625  2.         2.32192809]


In [38]:
print("log10(x)   :  ", np.log10(x))

log10(x)   :   [0.         0.30103    0.47712125 0.60205999 0.69897   ]


<b>Operations on multi-dimentional arrays <b>

In [39]:
x = np.array([[1,2,3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.add(x, 3)

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
np.subtract(x, 5)

array([[-4, -3, -2],
       [-1,  0,  1]])

In [42]:
np.power(x, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

<b> Comparison of ufuncs and for loops <b> 

In [44]:
def find_inverse(narray):
    inverse_list = []
    for number in narray:
        inverse_list.append(1/number)
    return np.array(inverse_list)      

In [45]:
big_array = np.random.randint(1, 100, size=1000)


In [47]:
%timeit find_inverse(big_array)

321 µs ± 2.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [48]:
%timeit (1 / big_array)

2.31 µs ± 33.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
find_inverse(big_array)

array([0.01785714, 0.33333333, 0.01515152, 0.5       , 0.01724138,
       0.03225806, 0.01428571, 0.01923077, 0.01282051, 0.125     ,
       0.03333333, 0.01333333, 0.01111111, 0.03333333, 0.01111111,
       0.05882353, 0.01724138, 0.11111111, 0.01923077, 0.01282051,
       0.03030303, 0.02702703, 0.03125   , 0.03571429, 0.01333333,
       0.02702703, 0.03030303, 0.08333333, 0.01886792, 0.01886792,
       0.08333333, 0.01369863, 0.02439024, 0.03030303, 0.02631579,
       0.25      , 0.01075269, 0.02173913, 0.04      , 0.0125    ,
       0.01149425, 0.01694915, 0.02040816, 0.07142857, 0.03125   ,
       0.03225806, 0.04545455, 0.01886792, 0.11111111, 0.01587302,
       0.08333333, 0.01162791, 0.03225806, 0.01075269, 0.01639344,
       0.25      , 0.01492537, 0.125     , 0.07692308, 0.09090909,
       0.01136364, 0.01162791, 0.0106383 , 0.01041667, 0.01298701,
       0.02222222, 0.01818182, 0.02702703, 0.14285714, 0.01538462,
       0.05555556, 0.02631579, 0.01785714, 0.01176471, 0.02040

In [51]:
1 / big_array

array([0.01785714, 0.33333333, 0.01515152, 0.5       , 0.01724138,
       0.03225806, 0.01428571, 0.01923077, 0.01282051, 0.125     ,
       0.03333333, 0.01333333, 0.01111111, 0.03333333, 0.01111111,
       0.05882353, 0.01724138, 0.11111111, 0.01923077, 0.01282051,
       0.03030303, 0.02702703, 0.03125   , 0.03571429, 0.01333333,
       0.02702703, 0.03030303, 0.08333333, 0.01886792, 0.01886792,
       0.08333333, 0.01369863, 0.02439024, 0.03030303, 0.02631579,
       0.25      , 0.01075269, 0.02173913, 0.04      , 0.0125    ,
       0.01149425, 0.01694915, 0.02040816, 0.07142857, 0.03125   ,
       0.03225806, 0.04545455, 0.01886792, 0.11111111, 0.01587302,
       0.08333333, 0.01162791, 0.03225806, 0.01075269, 0.01639344,
       0.25      , 0.01492537, 0.125     , 0.07692308, 0.09090909,
       0.01136364, 0.01162791, 0.0106383 , 0.01041667, 0.01298701,
       0.02222222, 0.01818182, 0.02702703, 0.14285714, 0.01538462,
       0.05555556, 0.02631579, 0.01785714, 0.01176471, 0.02040

<b> Comparision operators<b>

Comparison operators are also vectorisd operations.

In [53]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [55]:
x < 5

array([ True,  True,  True,  True, False])

In [56]:
x > 5

array([False, False, False, False, False])

In [57]:
x == 5

array([False, False, False, False,  True])

In [58]:
x != 5

array([ True,  True,  True,  True, False])

In [59]:
x <=5

array([ True,  True,  True,  True,  True])

In [60]:
x >=5

array([False, False, False, False,  True])

ufuncs are also available for comparison operators.

In [61]:
x

array([1, 2, 3, 4, 5])

In [62]:
np.equal(x, 5)

array([False, False, False, False,  True])

In [63]:
np.not_equal(x, 5)

array([ True,  True,  True,  True, False])

In [64]:
np.less(x, 5)

array([ True,  True,  True,  True, False])

In [65]:
np.greater(x, 5)

array([False, False, False, False, False])

In [68]:
x >= 5

array([False, False, False, False,  True])

In [67]:
np.greater_equal(x, 5)

array([False, False, False, False,  True])

In [75]:
np.less_equal(x, 5)

array([ True,  True,  True,  True,  True])

<b> Boolean Ufuncs<b>

In [75]:
np.random.random(size=(3,4))


array([[0.5700585 , 0.75159836, 0.942816  , 0.31413748],
       [0.85230667, 0.96582697, 0.49540535, 0.11749505],
       [0.17877492, 0.81983702, 0.43064496, 0.7528582 ]])

In [79]:
x = np.random.randint(10, size=(3,4))
x

array([[5, 8, 8, 0],
       [9, 2, 7, 8],
       [5, 8, 5, 2]])

We can use comparison operator like <, > etc on this array directly.

In [77]:
x > 5

array([[ True, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

The outcome matrix contains True/False for every element present in original matrix.

Following Ufuncs and boolean operators can be used on matrices. 

In [80]:
#counting number of elements fullfilling the condition
np.sum(x < 5)   # 6 entries in matrix which are less than 5

3

In [82]:
#counting number of elements fullfilling the condition, for each row
np.sum(x <= 5, axis = 1)   # 6 entries in matrix which are less than 5

array([2, 1, 3])

First row contains 3 elements, second row has one element whereas the third row has two elments fullfilling the condition.

In [83]:
#counting number of elements fullfilling the condition, for each row
np.sum(x < 5, axis = 0)   # 6 entries in matrix which are less than 5

array([0, 1, 0, 2])

First column contains 2 elements, second column has two element whereas the third column has one elments , fourth column contains one element fullfilling the condition.

One can determine whether any or all the values are true , np.any() and np.all() can be used.

In [85]:
np.all(x > 5)

False

Same operations can be done on row or column basis.

In [86]:
#Check for every row whether any value is greater than 5 or not
np.any(x > 5, axis = 1) 

array([ True,  True,  True])

In [87]:
#Check for every column whether any value is greater than 5 or not
np.any(x > 5, axis = 0) 

array([ True,  True,  True,  True])

<b> Boolean Operators<b>

Logical operators like &, ~ and | can be used as part of conditions.

In [88]:
x

array([[5, 8, 8, 0],
       [9, 2, 7, 8],
       [5, 8, 5, 2]])

In [89]:
#Determine how many elements have value greater than 5 and less than 8
np.sum( ( x > 5 ) & (x < 8))

1

In [91]:
#Determine how many elements have value equal t0 5 or 8
np.sum( ( x == 5 ) | (x == 8))

7

In [92]:
#Determine how many elements does not fullfill the given condition
np.sum( ~(( x == 5 ) | (x == 8)))

5

<b>Masking using Boolean Arrays <b>

In [23]:
x

array([[0, 4, 0, 5],
       [7, 5, 7, 0],
       [0, 4, 8, 8]])

Now need to find out how many elements have value less than 4.

In [93]:
x < 8

array([[ True, False, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True]])

But how to extract the actaul element values those are less than 8? This can be done using the indexing. This is called as masking.

In [94]:
x[ x < 8]  # returns one dimensional array having values less than 8

array([5, 0, 2, 7, 5, 5, 2])

Masks can be defined and used as part of ufuncs.

In [95]:
#Define a mask i.e. a condition based on which elements needs to be extracted
my_mask = x < 8  

In [96]:
#Use mask in the place of indexing
x[my_mask]

array([5, 0, 2, 7, 5, 5, 2])

Masks can be complicated conditions as well.

In [97]:
my_mask = (x < 8 ) & (x > 5)

In [98]:
#Use mask in the place of indexing
x[my_mask]

array([7])